# Generated by Django 4.2.7 on 2025-10-21 05:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                ("userId", models.CharField(max_length=255, unique=True)),
                (
                    "userType",
                    models.CharField(
                        choices=[
                            ("general", "일반"),
                            ("shop_owner", "소품샵"),
                            ("artist", "작가"),
                            ("admin", "관리자"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("phoneNumber", models.CharField(max_length=20)),
                ("name", models.CharField(max_length=255)),
                (
                    "profileImage",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("isActive", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
                ("updatedAt", models.DateTimeField(auto_now=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TermsAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("requiredTerms", models.BooleanField()),
                ("optionalTerms1", models.BooleanField()),
                ("optionalTerms2", models.BooleanField()),
                ("optionalTerms3", models.BooleanField()),
                ("agreedAt", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="BusinessInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("businessName", models.CharField(max_length=255)),
                ("businessRegistrationNumber", models.CharField(max_length=255)),
                ("businessAddress", models.CharField(max_length=255)),
                ("businessType", models.CharField(max_length=255)),
                ("businessCategory", models.CharField(max_length=255)),
                ("businessRegistrationFile", models.CharField(max_length=255)),
                ("interests", models.CharField(max_length=255)),
                ("bankName", models.CharField(max_length=255)),
                ("accountNumber", models.CharField(max_length=255)),
                ("accountHolder", models.CharField(max_length=255)),
                ("taxInvoiceEmail", models.EmailField(max_length=254)),
                (
                    "hometaxApiKey",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
