# Generated by Django 4.2.7 on 2025-10-21 05:40

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Artist",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "instagramId",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("description", models.TextField()),
                ("isActive", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("price", models.PositiveIntegerField()),
                ("stock", models.PositiveIntegerField()),
                ("description", models.TextField()),
                ("image", models.CharField(max_length=255)),
                ("category", models.CharField(max_length=255)),
                ("memo", models.TextField(blank=True, null=True)),
                ("isActive", models.BooleanField(default=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Shop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("phoneNumber", models.CharField(max_length=20)),
                ("address", models.CharField(max_length=255)),
                ("businessHours", models.TextField()),
                (
                    "instagramId",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("isActive", models.BooleanField(default=True)),
                ("createdAt", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
